INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`) VALUES ('Coca-Cola', 'Boisson');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`) VALUES ('Sprite', 'Sprite');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`) VALUES ('Oasis', 'Boisson');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`) VALUES ('Dr.Pepper', 'Boisson');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`) VALUES ('Ice Tea', 'Boisson');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`) VALUES ('San Pellegrino', 'Boisson');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`) VALUES ('Vin Rouge', 'Boisson');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`) VALUES ('Vin Rosé', 'Boisson');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`) VALUES ('8.6', 'Boisson');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`) VALUES ('Marguerite', 'Tomate, Fromage', 'Pizza');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`) VALUES ('La Reine ', 'Tomate, Jambon, Champignon', 'Pizza');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`) VALUES ('Chevre Miel', 'Crème, Chèvre, Miel', 'Pizza');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`) VALUES ('Orientale', 'Tomate, Merguez, Poivron, Oignon', 'Pizza');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`) VALUES ('Toscane', 'Tomate, Piment, Tomate Séchée, Poivron', 'Pizza');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`) VALUES ('Montagnarde', 'Oignon, Fromage à Raclette, Pomme de Terre', 'Pizza');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`) VALUES ('Norvégienne', 'Crème, Saumon Gravlax, Aneth', 'Pizza');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`) VALUES ('Pizza Suchi', 'Tomate, Sushi', 'Pizza');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`) VALUES ('C\'estCHO', 'Tomate, Piment, Poivre, Tabasco, Harissa', 'Pizza');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`) VALUES ('Bruschetta', 'Entrées');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`) VALUES ('Pain à l\'Ail', 'Entrées');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`) VALUES ('Nuggets', 'Entrées');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`) VALUES ('Potatoes', 'Entrées');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`) VALUES ('Salade', 'Entrées');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`) VALUES ('Calzone Nutella', 'Dessert');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`) VALUES ('glace', 'Dessert');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`) VALUES ('Cookie', 'Dessert');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`) VALUES ('Muffin', 'Dessert');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`) VALUES ('Donuts', 'Dessert');