INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Coca-Cola', 'Boisson', './asset/image/Boisson 1.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Sprite', 'Sprite', './asset/image/Boisson 3.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Oasis', 'Boisson', './asset/image/Boisson 2.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Dr.Pepper', 'Boisson', './asset/image/Boisson 1.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Ice Tea', 'Boisson', './asset/image/Boisson 1.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('San Pellegrino', 'Boisson', './asset/image/Boisson 2.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Vin Rouge', 'Boisson', './asset/image/Boisson 5.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Vin Rose', 'Boisson', './asset/image/Boisson 5.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('8.6', 'Boisson', './asset/image/Boisson 4.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`, `prix_prod`, `image_prod`) VALUES ('Marguerite', 'Tomate, Fromage', 'Pizza', '12,50', './asset/image/Pizzacarr1.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`, `prix_prod`, `image_prod`) VALUES ('La Reine ', 'Tomate, Jambon, Champignon', 'Pizza', '12,50', './asset/image/Pizzacarr2.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`, `prix_prod`, `image_prod`) VALUES ('Chevre Miel', 'Creme, Chevre, Miel', 'Pizza', '12,50', './asset/image/Pizzacarr1.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`, `prix_prod`, `image_prod`) VALUES ('Orientale', 'Tomate, Merguez, Poivron, Oignon', 'Pizza', '12,50', './asset/image/Pizzacarr3.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`, `prix_prod`, `image_prod`) VALUES ('Toscane', 'Tomate, Piment, Tomate Sechee, Poivron',  'Pizza', '12,50', './asset/image/Pizzacarr2.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`, `prix_prod`, `image_prod`) VALUES ('Montagnarde', 'Oignon, Fromage à Raclette, Pomme de Terre','Pizza', '12,50', './asset/image/Pizzacarr1.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`, `prix_prod`, `image_prod`) VALUES ('Norvegienne', 'Crème, Saumon Gravlax, Aneth', 'Pizza', '12,50', './asset/image/Pizzacarr3.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`, `prix_prod`, `image_prod`) VALUES ('Pizza Suchi', 'Tomate, Sushi', 'Pizza', '12,50', './asset/image/Pizzacarr2.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`, `prix_prod`, `image_prod`) VALUES ('C estCHO', 'Tomate, Piment, Poivre, Tabasco, Harissa', 'Pizza', '12,50', './asset/image/Pizzacarr3.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Bruschetta', 'Entrees', './asset/image/Sauce 1.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Pain à l Ail', 'Entrees', './asset/image/Sauce 3.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Nuggets', 'Entrees', './asset/image/Sauce 2.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Potatoes', 'Entrees', './asset/image/Sauce 3.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Salade', 'Entrees', './asset/image/Sauce 4.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Calzone Nutella', 'Dessert', './asset/image/Dessert 1.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('glace', 'Dessert', './asset/image/Dessert 1.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Cookie', 'Dessert', './asset/image/Dessert 3.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Muffin', 'Dessert', './asset/image/Dessert 02.webp');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Donuts', 'Dessert', './asset/image/Dessert 3.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`, `image_prod`) VALUES ('Pizza CUSTOM', 'Appelez nous pour customiser votre pizza', 'Pizza', './asset/image/Pizzacarr1.jpg');