INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Coca-Cola', 'Boisson', './asset/image/Boisson 1.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Sprite', 'Sprite', './asset/image/Boisson 3.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Oasis', 'Boisson', './asset/image/Boisson2.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Dr.Pepper', 'Boisson', './asset/image/Boisson 1.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Ice Tea', 'Boisson', './asset/image/Boisson 1.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('San Pellegrino', 'Boisson', './asset/image/Boisson 2.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Vin Rouge', 'Boisson', './asset/image/Boisson 5.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Vin Rosé', 'Boisson', './asset/image/Boisson 5.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('8.6', 'Boisson', '.\asset\image\Boisson 4.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`, `image_prod`) VALUES ('Marguerite', 'Tomate, Fromage', 'Pizza', './asset/image/Pizza 1.jpeg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`, `image_prod`) VALUES ('La Reine ', 'Tomate, Jambon, Champignon', 'Pizza', './asset/image/Pizza 2.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`, `image_prod`) VALUES ('Chevre Miel', 'Crème, Chèvre, Miel', 'Pizza', './asset/image/Pizza 1.jpeg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`, `image_prod`) VALUES ('Orientale', 'Tomate, Merguez, Poivron, Oignon', 'Pizza', './asset/image/Pizza 4.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`, `image_prod`) VALUES ('Toscane', 'Tomate, Piment, Tomate Séchée, Poivron', 'Pizza', './asset/image/Pizza 2.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`, `image_prod`) VALUES ('Montagnarde', 'Oignon, Fromage à Raclette, Pomme de Terre', 'Pizza', './asset/image/Pizza 1.jpeg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`, `image_prod`) VALUES ('Norvégienne', 'Crème, Saumon Gravlax, Aneth', 'Pizza', './asset/image/Pizza 3.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`, `image_prod`) VALUES ('Pizza Suchi', 'Tomate, Sushi', 'Pizza', './asset/image/Pizza 4.jpgg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `ingredient_prod`, `cat_prod`, `image_prod`) VALUES ('C\'estCHO', 'Tomate, Piment, Poivre, Tabasco, Harissa', 'Pizza', './asset/image/Pizza 3.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Bruschetta', 'Entrées', './asset/image/Sauce 1.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Pain à l\'Ail', 'Entrées', './asset/image/Sauce 3.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Nuggets', 'Entrées', './asset/image/Sauce 2.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Potatoes', 'Entrées', './asset/image/Sauce 3.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Salade', 'Entrées', './asset/image/Sauce 4.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Calzone Nutella', 'Dessert', './asset/image/Dessert 1.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('glace', 'Dessert', './asset/image/Dessert 1.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Cookie', 'Dessert', './asset/image/Dessert 3.jpg');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Muffin', 'Dessert', './asset/image/Dessert 02.webp');
INSERT INTO `pizzajeff`.`produits` (`nom_prod`, `cat_prod`, `image_prod`) VALUES ('Donuts', 'Dessert', './asset/image/Dessert 3.jpg');